#This script aims to perform ROI based tractography
#Loic Daumail - 30/01/2025
import os
import os.path as op
import matplotlib.pyplot as plt
import nibabel as nib
import plotly
import numpy as np
import ants

from AFQ.api.group import GroupAFQ
import AFQ.data.fetch as afd
from AFQ.definitions.image import RoiImage
import AFQ.api.bundle_dict as abd


##########################################################################
# Generate left MT ROI from freesurfer segmentation file
# ------------------------------------------------------------
# 1. Load the segmentation file that was generated by Freesurfer for
#    the specific subject.
# 2. Identify the left thalamus within the file, which has the label
#    number 41
# 3. Create a Nifti image representing the left thalamus ROI:
#    - Assign a value of 1 to the voxels that Freesurfer
#      has labeled as 41 (i.e., the left thalamus).
#    - Assign a value of 0 to all other voxels.
# This binary mask format is the expected input for pyAFQ when
# dealing with subject space ROIs. If it's already in binary format,
# there is no need to do this step.

#Creat only one set of MNI ROIs for the whole dataset

roi_path = os.path.expanduser("~/Documents/research/ampb_mt_tractometry_analysis/ampb/derivatives/glasser/mni_rois")
os.makedirs(roi_path, exist_ok=True)

#loop through participants
bids_path = os.path.expanduser("~/Documents/research/ampb_mt_tractometry_analysis/ampb")#anat"
preprocDir = op.join(bids_path, 'derivatives/qsiprep')

    # WORK_DIR = '~/Documents/research/ampb_mt_tractometry_analysis/ampb/work'
# Step 1: Load the Atlas Image
atlas_path = "~/Documents/research/brain_atlases/MNI2009a_GM_Glasser_2016/HCP-MMP1_on_MNI152_ICBM2009a_nlin_hd.nii.gz"  # Replace with your atlas file
atlas_img = ants.image_read(os.path.expanduser(atlas_path))

# Step 2: Define the ROI label (Check the atlas' label map for correct IDs)
roi_label = 23 | 2 | 157  # Replace with the label corresponding to your ROI: here hMT+

# Step 3: Create a Binary Mask for the ROI
roi_mask = atlas_img.numpy() == roi_label  # Boolean mask
roi_mask_img = ants.from_numpy(roi_mask.astype(np.uint8), origin=atlas_img.origin, spacing=atlas_img.spacing, direction=atlas_img.direction)

# Step 4: Extract ROI Voxel Values
# roi_voxel_values = atlas_img.numpy()[roi_mask]

#Left hemisphere MT ROI generation
lhMT_array = np.copy(roi_mask_img.numpy())
lhMT_array[:96, ...] = 0
lhMT_roi_mask = ants.from_numpy(lhMT_array.astype(np.uint8), origin=roi_mask_img.origin, spacing=roi_mask_img.spacing, direction=roi_mask_img.direction)

#Right hemisphere MT ROI generation
rhMT_array = np.copy(roi_mask_img.numpy())
rhMT_array[96:, ...] = 0
rhMT_roi_mask = ants.from_numpy(rhMT_array.astype(np.uint8), origin=roi_mask_img.origin, spacing=roi_mask_img.spacing, direction=roi_mask_img.direction)

# Save the LH MT ROI mask 
os.makedirs(op.join(roi_path), exist_ok=True)
roi_mask_path = op.join(roi_path,"space-MNI_desc-glasserlhmt_mask.nii.gz")
ants.image_write(lhMT_roi_mask, roi_mask_path)

roi_mask_path = op.join(roi_path, "space-MNI_desc-glasserrhmt_mask.nii.gz")
ants.image_write(rhMT_roi_mask, roi_mask_path)

#########        Generate PT ROI   #########
roi_label = 132 | 133 | 134 | 136 # Replace with the label corresponding to your ROI: here PT: 132 L_TE1a_ROI 133 L_TE1p_ROI 134 L_TE2a_ROI 136 L_TE2p_ROI

# Step 3: Create a Binary Mask for the ROI
roi_mask = atlas_img.numpy() == roi_label  # Boolean mask
roi_mask_img = ants.from_numpy(roi_mask.astype(np.uint8), origin=atlas_img.origin, spacing=atlas_img.spacing, direction=atlas_img.direction)

# Step 4: Extract ROI Voxel Values
# roi_voxel_values = atlas_img.numpy()[roi_mask]

#Left hemisphere PT ROI generation
lhPT_array = np.copy(roi_mask_img.numpy())
lhPT_array[:96, ...] = 0
lhPT_roi_mask = ants.from_numpy(lhPT_array.astype(np.uint8), origin=roi_mask_img.origin, spacing=roi_mask_img.spacing, direction=roi_mask_img.direction)

#Right hemisphere PT ROI generation
rhPT_array = np.copy(roi_mask_img.numpy())
rhPT_array[96:, ...] = 0
rhPT_roi_mask = ants.from_numpy(rhPT_array.astype(np.uint8), origin=roi_mask_img.origin, spacing=roi_mask_img.spacing, direction=roi_mask_img.direction)

# Save the LH PT ROI mask 
roi_mask_path = op.join(roi_path, "space-MNI_desc-glasserlhpt_mask.nii.gz")
ants.image_write(lhPT_roi_mask, roi_mask_path)
# Save the RH PT ROI mask
roi_mask_path = op.join(roi_path, "space-MNI_desc-glasserrhpt_mask.nii.gz")
ants.image_write(rhPT_roi_mask, roi_mask_path)
    
    ################## Run pyAFQ     ##################
bids_path = os.path.expanduser("~/Documents/research/ampb_mt_tractometry_analysis/ampb")#anat"
roi_path = os.path.expanduser("~/Documents/research/ampb_mt_tractometry_analysis/ampb/derivatives/glasser/mni_rois")

#Set tractography parameters
tracking_params = dict(n_seeds=10000,
                    random_seeds=True,
                    rng_seed=42,
                    seed_mask=RoiImage(use_endpoints=True))
#Define custom bundle dict
bundles = abd.BundleDict({
    "L_OR": {
        "include": [
            op.join(roi_path, "space-MNI_desc-glasserlhmt_mask.nii.gz"),
            op.join(roi_path, "space-MNI_desc-glasserlhpt_mask.nii.gz"),
        ],
        "cross_midline": False,
        "space": "template"
    }})
#Initialize groupAFQ object
myafq = GroupAFQ(
    bids_path=bids_path,
    preproc_pipeline='qsiprep',
    tracking_params=tracking_params,
    bundle_info=bundles)

bundle_html = myafq.export("all_bundles_figure")
# bundle_html = myafq.export("all")
# bundle_html = myafq.export("indiv_bundles_figures")
# plotly.io.show(bundle_html["NSxLxPQx1973"]["L_OR"])


#Create ROI directory for specific ROIs
# roi_path = os.path.expanduser("~/Documents/research/ampb_mt_tractometry_analysis/ampb/derivatives/glasser")
# os.makedirs(roi_path, exist_ok=True)

# #loop through participants
# bids_path = os.path.expanduser("~/Documents/research/ampb_mt_tractometry_analysis/ampb")#anat"
# preprocDir = op.join(bids_path, 'derivatives/qsiprep')
# subjNames = [f for f in os.listdir(preprocDir) if f not in {".DS_Store", "dataset_description.json", "dwiqc.json","logs",".bidsignore"} and not f.endswith((".html"))]
# # Loop through each subject folder in the directory
# for participant in subjNames:

#     # WORK_DIR = '~/Documents/research/ampb_mt_tractometry_analysis/ampb/work'

#     # Step 1: Load the Atlas Image
#     atlas_path = "~/Documents/research/brain_atlases/MNI2009a_GM_Glasser_2016/HCP-MMP1_on_MNI152_ICBM2009a_nlin_hd.nii.gz"  # Replace with your atlas file
#     atlas_img = ants.image_read(os.path.expanduser(atlas_path))

#     # Step 2: Define the ROI label (Check the atlas' label map for correct IDs)
#     roi_label = 23 | 2 | 157  # Replace with the label corresponding to your ROI: here hMT+

#     # Step 3: Create a Binary Mask for the ROI
#     roi_mask = atlas_img.numpy() == roi_label  # Boolean mask
#     roi_mask_img = ants.from_numpy(roi_mask.astype(np.uint8), origin=atlas_img.origin, spacing=atlas_img.spacing, direction=atlas_img.direction)

#     # Step 4: Extract ROI Voxel Values
#     roi_voxel_values = atlas_img.numpy()[roi_mask]



#     # Step 5: Resample ROI to ACPC space
#     # FIXED_QSIPREPT1 = os.path.expanduser(op.join("~/Documents/research/ampb_mt_tractometry_analysis/ampb/derivatives/qsiprep", participant ,"anat", participant+"_space-ACPC_desc-preproc_T1w.nii.gz"))
#     # qsiprep_t1 = ants.image_read(FIXED_QSIPREPT1)

#     # mytx = os.path.expanduser(op.join("~/Documents/research/ampb_mt_tractometry_analysis/ampb/derivatives/qsiprep", participant ,"anat", participant+"_from-MNI152NLin2009cAsym_to-ACPC_mode-image_xfm.h5"))
    
    
#     # roi_mask_img_warped = ants.apply_transforms( fixed = qsiprep_t1, 
#     #                                     moving = roi_mask_img, 
#     #                                     transformlist = mytx,                                       
#     #                                     interpolator  = 'genericLabel', 
#     #                                     ) #whichtoinvert = [True, False]
#     #Left hemisphere MT ROI generation
#     # lhMT_array = np.copy(roi_mask_img_warped.numpy())
#     # lhMT_array[:96, ...] = 0
#     # lhMT_roi_mask = ants.from_numpy(lhMT_array.astype(np.uint8), origin=roi_mask_img_warped.origin, spacing=roi_mask_img_warped.spacing, direction=roi_mask_img_warped.direction)

#     #Right hemisphere MT ROI generation
#     # rhMT_array = np.copy(roi_mask_img_warped.numpy())
#     # rhMT_array[96:, ...] = 0
#     # rhMT_roi_mask = ants.from_numpy(rhMT_array.astype(np.uint8), origin=roi_mask_img_warped.origin, spacing=roi_mask_img_warped.spacing, direction=roi_mask_img_warped.direction)
 
#     #Left hemisphere MT ROI generation
#     lhMT_array = np.copy(roi_mask_img.numpy())
#     lhMT_array[:96, ...] = 0
#     lhMT_roi_mask = ants.from_numpy(lhMT_array.astype(np.uint8), origin=roi_mask_img.origin, spacing=roi_mask_img.spacing, direction=roi_mask_img.direction)

#     #Right hemisphere MT ROI generation
#     rhMT_array = np.copy(roi_mask_img.numpy())
#     rhMT_array[96:, ...] = 0
#     rhMT_roi_mask = ants.from_numpy(rhMT_array.astype(np.uint8), origin=roi_mask_img.origin, spacing=roi_mask_img.spacing, direction=roi_mask_img.direction)


#     # warpedData = roi_mask_img_warped.numpy()
#     # fig, ax = plt.subplots(1)
#     # ax.matshow(warpedData[:, :,14], cmap='viridis')
#     # ax.axis("off")
#     # Save the LH MT ROI mask 
#     os.makedirs(op.join(roi_path, participant ,"ses-03","anat"), exist_ok=True)
#     roi_mask_path = op.join(roi_path, participant ,"ses-03","anat", participant+"_ses-03_space-ACPC_desc-glasserlhmt_mask.nii.gz")
#     ants.image_write(lhMT_roi_mask, roi_mask_path)

#     roi_mask_path = op.join(roi_path, participant ,"ses-03","anat", participant+"_ses-03_space-ACPC_desc-glasserrhmt_mask.nii.gz")
#     ants.image_write(rhMT_roi_mask, roi_mask_path)

#     #########        Generate PT ROI   #########
#     roi_label = 132 | 133 | 134 | 136 # Replace with the label corresponding to your ROI: here PT: 132 L_TE1a_ROI 133 L_TE1p_ROI 134 L_TE2a_ROI 136 L_TE2p_ROI

#     # Step 3: Create a Binary Mask for the ROI
#     roi_mask = atlas_img.numpy() == roi_label  # Boolean mask
#     roi_mask_img = ants.from_numpy(roi_mask.astype(np.uint8), origin=atlas_img.origin, spacing=atlas_img.spacing, direction=atlas_img.direction)

#     # Step 4: Extract ROI Voxel Values
#     roi_voxel_values = atlas_img.numpy()[roi_mask]


#     # Step 5: Resample ROI to ACPC space
#     # FIXED_QSIPREPT1 = os.path.expanduser(op.join("~/Documents/research/ampb_mt_tractometry_analysis/ampb/derivatives/qsiprep", participant ,"anat", participant+"_space-ACPC_desc-preproc_T1w.nii.gz"))
#     # qsiprep_t1 = ants.image_read(FIXED_QSIPREPT1)

#     # mytx = os.path.expanduser(op.join("~/Documents/research/ampb_mt_tractometry_analysis/ampb/derivatives/qsiprep", participant ,"anat", participant+"_from-MNI152NLin2009cAsym_to-ACPC_mode-image_xfm.h5"))
    

#     # roi_mask_img_warped = ants.apply_transforms( fixed = qsiprep_t1, 
#     #                                     moving = roi_mask_img, 
#     #                                     transformlist = mytx,                                       
#     #                                     interpolator  = 'genericLabel', 
#     #                                     ) #whichtoinvert = [True, False]
#     # #Left hemisphere PT ROI generation
#     # lhPT_array = np.copy(roi_mask_img_warped.numpy())
#     # lhPT_array[:96, ...] = 0
#     # lhPT_roi_mask = ants.from_numpy(lhPT_array.astype(np.uint8), origin=roi_mask_img_warped.origin, spacing=roi_mask_img_warped.spacing, direction=roi_mask_img_warped.direction)

#     # #Right hemisphere PT ROI generation
#     # rhPT_array = np.copy(roi_mask_img_warped.numpy())
#     # rhPT_array[96:, ...] = 0
#     # rhPT_roi_mask = ants.from_numpy(rhPT_array.astype(np.uint8), origin=roi_mask_img_warped.origin, spacing=roi_mask_img_warped.spacing, direction=roi_mask_img_warped.direction)
    
#     #Left hemisphere PT ROI generation
#     lhPT_array = np.copy(roi_mask_img.numpy())
#     lhPT_array[:96, ...] = 0
#     lhPT_roi_mask = ants.from_numpy(lhPT_array.astype(np.uint8), origin=roi_mask_img.origin, spacing=roi_mask_img.spacing, direction=roi_mask_img.direction)

#     #Right hemisphere PT ROI generation
#     rhPT_array = np.copy(roi_mask_img.numpy())
#     rhPT_array[96:, ...] = 0
#     rhPT_roi_mask = ants.from_numpy(rhPT_array.astype(np.uint8), origin=roi_mask_img.origin, spacing=roi_mask_img.spacing, direction=roi_mask_img.direction)

#     # warpedData = roi_mask_img_warped.numpy()
#     # fig, ax = plt.subplots(1)
#     # ax.matshow(warpedData[:, :,14], cmap='viridis')
#     # ax.axis("off")
#     # Save the LH PT ROI mask 
#     roi_mask_path = op.join(roi_path, participant,"ses-03", "anat", participant+"_ses-03_space-ACPC_desc-glasserlhpt_mask.nii.gz")
#     ants.image_write(lhPT_roi_mask, roi_mask_path)
#     # Save the RH PT ROI mask
#     roi_mask_path = op.join(roi_path, participant,"ses-03", "anat", participant+"_ses-03_space-ACPC_desc-glasserrhpt_mask.nii.gz")
#     ants.image_write(rhPT_roi_mask, roi_mask_path)
    
    ################## Run pyAFQ     ##################
bids_path = os.path.expanduser("~/Documents/research/ampb_mt_tractometry_analysis/ampb")#anat"
roi_path = os.path.expanduser("~/Documents/research/ampb_mt_tractometry_analysis/ampb/derivatives/glasser")

#Set tractography parameters
tracking_params = dict(n_seeds=10000,
                    random_seeds=True,
                    rng_seed=42,
                    seed_mask=RoiImage(use_endpoints=True))
#Define custom bundle dict
bundles = abd.BundleDict({
    "L_OR": {
        "start": {
            "scope": "glasser",
            "suffix": "mask",
            "desc": "glasserlhmt"},
        "end": {
            "scope": "glasser",
            "suffix": "mask",
            "desc": "glasserlhpt"
        },
        "cross_midline": False,
        "space": "template"
    }})
#Initialize groupAFQ object
myafq = GroupAFQ(
    bids_path=bids_path,
    preproc_pipeline='qsiprep',
    tracking_params=tracking_params,
    bundle_info=bundles)

bundle_html = myafq.export("indiv_bundles_figures")
plotly.io.show(bundle_html["01"]["L_OR"])




###Remove files
# target_pattern = "desc-glasser"

# # Loop through all subject directories
# for participant in subjNames:
#     subject_dir = os.path.join(preprocDir, participant,"anat")
    
#     # Ensure it's a directory
#     if os.path.isdir(subject_dir):  
#         for file in os.listdir(subject_dir):
#             # Check if the file starts with the target base name
#             if target_pattern in file:
#                 file_path = os.path.join(subject_dir, file)
#                 print(f"Removing: {file_path}")
#                 os.remove(file_path)


########
#     freesurfer_subject_folder = os.path.expanduser(op.join(
#         "~", "Documents", "research", "ampb_mt_tractometry_analysis",
#         "ampb", "derivatives", "freesurfer",
#         participant,
#         "mri"))

#     seg_file = nib.load(op.join(
#         freesurfer_subject_folder, "aparc.a2009s+aseg.mgz"))
#     left_MT = seg_file.get_fdata() == 1015
#     nib.save(
#         nib.Nifti1Image(
#             left_MT.astype(np.float32),
#             seg_file.affine),
#         op.join(
#             freesurfer_subject_folder,
#             participant+"_leftMT_mask.nii.gz"))

# # Fetch LV1 ROI
# # which was already generated using the process above
# afd.fetch_stanford_hardi_lv1()

# import os.path as 

# import plotly
# import numpy as np
# import shutil

# from AFQ.api.group import GroupAFQ
# import AFQ.api.bundle_dict as abd
# from AFQ.definitions.image import ImageFile, RoiImage
# np.random.seed(1234)

# ROI_DIR = '/Users/ldaumail3/Documents/research/ampb_mt_tractometry_analysis/ampb/work/sub-NSxGxHNx1952/MT_roi_glasser_mask_space-ACPC.nii.gz'
# BIDS_DIR = '/Users/ldaumail3/Documents/research/ampb_mt_tractometry_analysis/ampb'
# bundles = abd.BundleDict({
#     "MT": {
#         "include": [
#             ROI_DIR],
#         "exclude": [
#            ],

#         "cross_midline": False,

#         "mahal": {
#             "clean_rounds": 20,
#             "length_threshold": 4,
#             "distance_threshold": 2}
#     }})

# brain_mask_definition = ImageFile(
#     suffix="mask",
#     filters={'desc': 'brain',
#              'space': 'T1w',
#              'scope': 'qsiprep'})

# my_afq = GroupAFQ(
#     bids_path=BIDS_DIR,
#     preproc_pipeline="qsiprep",
#     output_dir=op.join(BIDS_DIR, "derivatives", "afq_MT"),
#     brain_mask_definition=brain_mask_definition,
#     tracking_params={"n_seeds": 10,
#                      "directions": "prob",
#                      "odf_model": "CSD",
#                      "seed_mask": RoiImage()},
#     segmentation_params={"parallel_segmentation": {"engine": "serial"}},
#     bundle_info=bundles)

# my_afq.export_all()
