#This script aims to perform ROI based tractography
#Loic Daumail - 30/01/2025
import os
import os.path as op
import matplotlib.pyplot as plt
import nibabel as nib
import plotly
import numpy as np
import ants
import sys

utils = '/Users/ldaumail3/Documents/research/ampb_mt_tractometry_analysis/ampb/code/utils'
sys.path.append(op.expanduser(f'{utils}'))

from AFQ.api.group import GroupAFQ
import AFQ.data.fetch as afd
from AFQ.definitions.image import RoiImage
import AFQ.api.bundle_dict as abd


##########################################################################
# Generate left MT ROI from freesurfer segmentation file
# ------------------------------------------------------------
# 1. Load the segmentation file that was generated by Freesurfer for
#    the specific subject.
# 2. Identify the left thalamus within the file, which has the label
#    number 41
# 3. Create a Nifti image representing the left thalamus ROI:
#    - Assign a value of 1 to the voxels that Freesurfer
#      has labeled as 41 (i.e., the left thalamus).
#    - Assign a value of 0 to all other voxels.
# This binary mask format is the expected input for pyAFQ when
# dealing with subject space ROIs. If it's already in binary format,
# there is no need to do this step.

# ROI directory (freesurfer derivatives directory)
roi_path = os.path.expanduser("~/Documents/research/ampb_mt_tractometry_analysis/ampb/derivatives/qsiprep")
os.makedirs(roi_path, exist_ok=True)

#loop through participants
bids_path = os.path.expanduser("~/Documents/research/ampb_mt_tractometry_analysis/ampb")#anat"
preprocDir = op.join(bids_path, 'derivatives/qsiprep')
subjNames = [f for f in os.listdir(preprocDir) if f not in {".DS_Store", "dataset_description.json", "dwiqc.json","logs",".bidsignore"} and not f.endswith((".html"))]
# Loop through each subject folder in the directory
for participant in subjNames:

    freesurfer_subject_folder = os.path.expanduser(op.join("~/Documents/research/ampb_mt_tractometry_analysis/ampb/derivatives/freesurfer_reconall", participant, "mri"))
    for session in ["ses-03", "ses-04"]:
    # #Create ROI using ants
    ## We need to convert fs segmentation .mgz to nifti format before using nibabel
    # # Save directory with NIfTI format
    # FS_SEG_MGZ = op.join(freesurfer_subject_folder, "aparc.a2009s+aseg.mgz")
    # FS_SEG_NII = op.join(freesurfer_subject_folder, "aparc.a2009s+aseg.nii.gz")
    # # Run mri_convert
    # freesurferCommand = f'mri_convert {FS_SEG_MGZ} {FS_SEG_NII}'
    # os.system(f'bash {utils}/callFreesurferFunction.sh -s "{freesurferCommand}"')
    # atlas_img = ants.image_read(op.join(freesurfer_subject_folder, "aparc.a2009s+aseg.nii.gz")) #nib.load(op.join(freesurfer_subject_folder, "aparc.a2009s+aseg.nii.gz"))
    # roi_label = 11138
    # lhMT_roi_mask = atlas_img.numpy() == roi_label  # Boolean mask
    # roi_mask_img = ants.from_numpy(lhMT_roi_mask.astype(np.uint8), origin=atlas_img.origin, spacing=atlas_img.spacing, direction=atlas_img.direction)
    # roi_mask_path = op.join(roi_path, participant, "mri", participant+"_ses-01_desc-lhMT_mask.nii.gz")
    # ants.image_write( roi_mask_img, roi_mask_path)
    # np.all(lhMT_roi_mask==0)
    #unique_labels = np.unique(atlas_img.numpy()).astype(np.uint8)


        #Create left MT ROI using nibabel
        seg_file = nib.load(op.join(
            freesurfer_subject_folder, "aparc.a2009s+aseg.mgz"))
        left_MT = seg_file.get_fdata() == 11138

        roi_mask_path = op.join(roi_path, participant,session, "anat")
        os.makedirs(roi_mask_path, exist_ok=True)
        nib.save(
            nib.Nifti1Image(
                left_MT.astype(np.float32),
                seg_file.affine),
            op.join( 
                roi_mask_path,
                participant+"_"+session+"_desc-leftMT_mask.nii.gz"))

        #Create right MT ROI using nibabel
        right_MT = seg_file.get_fdata() == 12138

        nib.save(
            nib.Nifti1Image(
                right_MT.astype(np.float32),
                seg_file.affine),
            op.join( 
                roi_mask_path,
                participant+"_"+session+"_desc-rightMT_mask.nii.gz"))

        #Create left PT
        left_PT = seg_file.get_fdata() == 11136
        nib.save(
            nib.Nifti1Image(
                left_PT.astype(np.float32),
                seg_file.affine),
            op.join( 
                roi_mask_path,
                participant+"_"+session+"_desc-leftPT_mask.nii.gz"))

        #Create right PT ROI using nibabel

        right_PT = seg_file.get_fdata() == 12136

        nib.save(
            nib.Nifti1Image(
                right_PT.astype(np.float32),
                seg_file.affine),
            op.join( 
                roi_mask_path,
                participant+"_"+session+"_desc-rightPT_mask.nii.gz"))

for participant in subjNames:

    freesurfer_subject_folder = os.path.expanduser(op.join("~/Documents/research/ampb_mt_tractometry_analysis/ampb/derivatives/freesurfer_reconall", participant, "mri"))
    for session in ["ses-03", "ses-04"]:
 # Copy and rename anatomical to freesurfer ROI folder
        roi_mask_path = op.join(roi_path, participant,session, "anat")
        os.makedirs(roi_mask_path, exist_ok=True) 
        FS_T1 = op.join(freesurfer_subject_folder, "T1.mgz")
        FS_T1_copy = op.join(roi_mask_path, participant+"_"+session+"_desc-freesurfer_T1w.nii.gz")
        # Run mri_convert
        freesurferCommand = f'mri_convert {FS_T1} {FS_T1_copy}'
        os.system(f'bash {utils}/callFreesurferFunction.sh -s "{freesurferCommand}"')


    ################## Run pyAFQ     ##################
bids_path = os.path.expanduser("~/Documents/research/ampb_mt_tractometry_analysis/ampb")#anat"
# roi_path = os.path.expanduser("~/Documents/research/ampb_mt_tractometry_analysis/ampb/derivatives/freesurfer")

#Set tractography parameters
tracking_params = dict(n_seeds=10000,
                    random_seeds=True,
                    rng_seed=42,
                    seed_mask=RoiImage(use_endpoints=True))
#Define custom bundle dict
bundles = abd.BundleDict({
    "L_OR": {
        "start": {
            "scope": "freesurfer",
            "suffix": "mask",
            "desc": "lhMT"},
        "end": {
            "scope": "freesurfer",
            "suffix": "mask",
            "desc": "lhPT"
        },
        "cross_midline": False,
        "space": "subject"
    }})
#Initialize groupAFQ object
myafq = GroupAFQ(
    bids_path=bids_path,
    preproc_pipeline='qsiprep',
    tracking_params=tracking_params,
    bundle_info=bundles)

bundle_html = myafq.export("indiv_bundles_figures")
plotly.io.show(bundle_html["01"]["L_OR"])




###Remove files
# target_pattern = "T1w"

# Loop through all subject directories
# for participant in subjNames:
#     for session in ["ses-03", "ses-04"]:
#         subject_dir = os.path.join(preprocDir, participant, session, "anat")
        
#         # Ensure it's a directory
#         if os.path.isdir(subject_dir):  
#             for file in os.listdir(subject_dir):
#                 # Check if the file starts with the target base name
#                 if target_pattern in file:
#                     file_path = os.path.join(subject_dir, file)
#                     print(f"Removing: {file_path}")
#                     os.remove(file_path)

# ### Remove folders and contents
# import shutil 
# for participant in subjNames:
#     for session in ["ses-03", "ses-04"]:
#         subject_dir = os.path.join(preprocDir, participant, session, "anat")

#         if os.path.exists(subject_dir):
#             shutil.rmtree(subject_dir)

########
#     freesurfer_subject_folder = os.path.expanduser(op.join(
#         "~", "Documents", "research", "ampb_mt_tractometry_analysis",
#         "ampb", "derivatives", "freesurfer",
#         participant,
#         "mri"))

#     seg_file = nib.load(op.join(
#         freesurfer_subject_folder, "aparc.a2009s+aseg.mgz"))
#     left_MT = seg_file.get_fdata() == 1015
#     nib.save(
#         nib.Nifti1Image(
#             left_MT.astype(np.float32),
#             seg_file.affine),
#         op.join(
#             freesurfer_subject_folder,
#             participant+"_leftMT_mask.nii.gz"))

# # Fetch LV1 ROI
# # which was already generated using the process above
# afd.fetch_stanford_hardi_lv1()

# import os.path as 

# import plotly
# import numpy as np
# import shutil

# from AFQ.api.group import GroupAFQ
# import AFQ.api.bundle_dict as abd
# from AFQ.definitions.image import ImageFile, RoiImage
# np.random.seed(1234)

# ROI_DIR = '/Users/ldaumail3/Documents/research/ampb_mt_tractometry_analysis/ampb/work/sub-NSxGxHNx1952/MT_roi_glasser_mask_space-ACPC.nii.gz'
# BIDS_DIR = '/Users/ldaumail3/Documents/research/ampb_mt_tractometry_analysis/ampb'
# bundles = abd.BundleDict({
#     "MT": {
#         "include": [
#             ROI_DIR],
#         "exclude": [
#            ],

#         "cross_midline": False,

#         "mahal": {
#             "clean_rounds": 20,
#             "length_threshold": 4,
#             "distance_threshold": 2}
#     }})

# brain_mask_definition = ImageFile(
#     suffix="mask",
#     filters={'desc': 'brain',
#              'space': 'T1w',
#              'scope': 'qsiprep'})

# my_afq = GroupAFQ(
#     bids_path=BIDS_DIR,
#     preproc_pipeline="qsiprep",
#     output_dir=op.join(BIDS_DIR, "derivatives", "afq_MT"),
#     brain_mask_definition=brain_mask_definition,
#     tracking_params={"n_seeds": 10,
#                      "directions": "prob",
#                      "odf_model": "CSD",
#                      "seed_mask": RoiImage()},
#     segmentation_params={"parallel_segmentation": {"engine": "serial"}},
#     bundle_info=bundles)

# my_afq.export_all()
